name: Pipeline de CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'julioarruda.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo development deploy successfully executed!
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'julioarruda.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo homologation deployment successfully performed!
        
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'julioarruda.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo production deploy successfully executed!

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello!
